#include<iostream>
#include<string>
#include<fstream>
#include<stdlib.h>
using namespace std;

int main() {

cout<< " Welcome to game where you have to gusess\n";
cout<< " the number that was randomly generated by a machine\n";
cout<<" "<<endl;
cout<<"Enter a max random number: ";
int randN;
cin>>randN;

int enGangTil=true;
int antRunder=0;

while (enGangTil=1){
  antRunder++;
  int gjettinger=1;
  int randNum=(rand()%randN);
  cout<<"What is you guess? ";
  int guess;
  cin>>guess;
    while (randNum != guess) {
      if (guess<randNum) {
        cout<<"To low\n";
        cout<<"What is you guess? \n";
        int guess;
        gjettinger++;
      }
      else if(guess>randNum){
        cout<<"To high\n";
        cout<<"What is you guess? \n";
        int guess;
        gjettinger++;
      }
    }
  cout<<"That is correct!\n";
  cout<<"It took you "<<gjettinger<<" tryes to guess right\n";
}
}
