#include<iostream>
#include<string>
#include<fstream>
#include<stdlib.h>
using namespace std;

int main() {

cout<<" "<<endl;
cout<<"Welcome to guessing game!\n";
cout<<"Try guessing number that was randomly generated by a machine.\n";
 cout<<"Number generated will be in range from 1 to N\n";
cout<<" "<<endl;
cout<<"Enter a max number (N) you wish to be generated: ";
int randN;
cin>>randN;

int enGangTil=1;
int antRunder=0;
int totGjett=0;

  while (enGangTil==1){
    antRunder++;
    int gjettinger=1;
    int randNum=(rand()%randN);
    cout<<"What is you guess? ";
    int guess;
    cin>>guess;
      while (randNum != guess) {
        if (guess<randNum) {
          cout<<"To low\n";
          cout<<"What is you guess: ";
          cin>>guess;
          gjettinger++;
        }
        else if(guess>randNum){
          cout<<"To high\n";
          cout<<"What is you guess: ";
          cin>>guess;
          gjettinger++;
        }
      }
    totGjett=totGjett+gjettinger;

    cout<<"That is correct!\n";
    cout<<"It took you "<<gjettinger<<" attempts to guess right\n";
    if (gjettinger<5) {
      cout<<"You had less than 5 attempts, you did well!\n";
    }
    else {
      cout<<"You had more than 5 attempts, try doing a better job next time!\n";
    }
    cout<<"Do you want to continue playing? [Y/n]: ";
    char answer;
    cin>>answer;

    while (answer !='N' && answer!='n' && answer!='Y' && answer!='y') {
      std::cout << "Please type Y or n: ";
      cin>>answer;
    }

    if (answer=='y' || answer=='Y'){
      enGangTil=1;
    }
    else {
      enGangTil=0;
    }
  }
  int Average=totGjett/antRunder;
  cout<<"Hope you had a nice time playing!\n";
  cout<<"Douring " <<antRunder<<" round you played, \n";
  cout<<"your average was "<<Average<<" attempts per round.\n";
  cout<<" "<<endl;
}
